---
title: "R Notebook"
output: html_notebook
---
```{r}
library(zoo)
library(tseries)
library(urca)
```

```{r}
df <- read.csv("valeurs_mensuelles_jus.csv", sep = ";", skip=3)
df <- df[, 1:2]
colnames(df) <- c("DATE", "VALUES")
```

```{r}
df$DATE <- as.Date(paste(df$DATE, "-01", sep=""), format="%Y-%m-%d")
time_series_zoo <- zoo(df$VALUES, order.by = df$DATE)
head(time_series_zoo)
```
```{r}
plot(time_series_zoo, type = "l", col = "blue", lwd = 2, 
     xlab = "Date", ylab = "Values", 
     main = "Time Series Plot of values")
```
```{r}
times_series=ts(time_series_zoo, frequency = 12)
head(times_series)
```
```{r}
acf(times_series)
pacf(times_series)
```
```{r}
time_series_zoo_diff <- diff(time_series_zoo)
plot(time_series_zoo_diff, type = "l", col = "blue", lwd = 2, 
     xlab = "Time", ylab = "Differenced Values", 
     main = "Differenced Time Series")
```
```{r}
adf_test_result <- adf.test(time_series_zoo_diff, alternative = "stationary")
adf_test_result
```
```{r}
times_series_diff=ts(time_series_zoo_diff, frequency = 12)
acf(times_series_diff)
pacf(times_series_diff)
```

